### ISSUE TITLE
simhub changed settings of thrustmaster control panel

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#171] opened 2017-11-16 21:20 UTC
Just a heads up,

Simhub changed my centering mode when I installed the latest version.

**Comment by zegreatclan** [comment] 2017-11-16 21:50
Hi ! You mean the game/vs wheel option ? Or the center force ?

**Comment by Meekstaaa** [comment] 2017-11-16 21:51
Yeah game vs wheel.

Many thanks

David Meek
Sent from my iPhone

On 16 Nov 2017, at 21:50, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi ! You mean the game/vs wheel option ? Or the center force ?

**Comment by Meekstaaa** [comment] 2017-11-17 21:01
FYI - Noticed everytime you switch between games in simhub it deselects both options which in turn selects 'from the wheel' in the thrustmaster control panel.

**Comment by zegreatclan** [comment] 2017-11-17 22:18
Indeed there was some weird things
It should be fixed for next release

**Comment by zegreatclan** [comment] 2017-11-26 09:40
I can't reproduce it anymore since the last fix, i close for now, do not heistate if you still see something weird

**Closed by zegreatclan** 2017-11-26 09:40 UTC
Labels: bug, Done
